finished changes on spreadsheet
enviro-issues/south-downtown-hub-po pull request #5
Opened 2024-01-06 00:32 UTC by ihateerrors

A decent amount of changes with fonts, styles and added a lot of content as well. Changed layout of the site.  Header needs a bit of a work, took too much time figuring out best layout, need a second eye.

2024-01-06 01:01 UTC, benbogard commented on css/base.css
> +  src: url('path/to/fonts/Bahnschrift-Regular.woff2') format('woff2'),
path to... where?

2024-01-06 01:02 UTC, benbogard commented on css/base.css
> +  font-style: normal !important;
can we push this style further down the cascade so that !important is not needed?

2024-01-06 01:06 UTC, benbogard commented on south-pine-street.html
> +                  href="https://www.soundtransit.org/system-expansion/lakewood-station-access-improvements "
extra space on the end of the url

2024-01-06 01:08 UTC, benbogard requested changes
@Gengur123 added some comments/questions. Reckon we should fold in the actual fonts into the codebase within this PR. Also, it is !important to do our best to not use !important ;)

2024-01-08 17:36 UTC, ihateerrors commented on css/base.css
> +  src: url('path/to/fonts/Bahnschrift-Regular.woff2') format('woff2'),
Fonts weights were kinda strange, was trying to find a way around this but this definitely wasn't it hahaha

2024-01-08 21:50 UTC, benbogard approved these changes

2024-01-08 21:51 UTC, merged